version: '3'
services:
  ollama-container:
    image: docker.io/ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.podman
    image: localhost/rudrakshkarpe/gsoc-2024:latest
    container_name: llm-localization-app
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_BASE_URL=http://ollama-container:11434
    depends_on:
      - ollama-container

volumes:
  ollama-data: 